### ISSUE TITLE
Checklist para atualização do repositório

### ISSUE THREAD

**Issue by Ronkiro** [Ronkiro/UniCarioca-IT-Introduction#1]
### Olá, seja bem-vindo ao lado negro da força.

> Este repositório não tem vínculos com a instituição. É feito por estudantes. Para estudantes..

Este repositório foi criado para auxiliar os estudantes de matérias relacionadas à área de computação da UniCarioca que sentem alguma dificuldade em ingressar no mercado.

O objetivo deste repositório **NÃO É** ensinar como passar mais facilmente em matérias da UniCarioca, mas sim complementar seus estudos com assuntos que na maioria das vezes não são explorados em sala de aula.

Caso você já tenha experiência, estarei feliz em poder ter seu auxílio para construir este repositório. Leia mais abaixo caso queira ajudar.

### O que falta neste repositório:
- [x] **Introdução ao Markdown**
- [ ] **Introdução ao Git + Dicas + Como auxiliar este repo**
- [ ] **Newbie FAQ** - Um FAQ para o pessoal que está começando, e não teve muito contato com computação
- [ ] **FAQ** - Um FAQ para quem já tem certo conhecimento, mas ainda tem algumas dúvidas que são comuns.
- [ ] **Dicas de estudo** - O que estudar, quando estudar e como estudar?
- [ ] **Atualizar README.md** - Isto eu mesmo farei ;)
- [ ] **Dicas de conteúdo para dev e matérias relacionadas**
- [ ] **Dicas de conteúdo para Infra/Suporte e matérias relacionadas**
- [ ] **Dicas de conteúdo para InfoSec  e matérias relacionadas**

Conteúdo extra poderá ser adicionado posteriormente. Estes são P0

**Comment by Ronkiro** [comment]
Caso tenha interesse em adicionar algum conteúdo extra, por favor abrir um issue comentando o tipo de conteúdo. Para contribuir, fique à vontade para abrir um Pull Request da sua forma até que um documento CONTRIBUTING.md seja escrito e padronize este processo.
